"""增加了一行confirmed Boolean

Revision ID: 40dad3a0c5a2
Revises: bd4f91633b10
Create Date: 2020-04-21 20:48:01.571663

"""

# revision identifiers, used by Alembic.
revision = '40dad3a0c5a2'
down_revision = 'bd4f91633b10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
