"""empty message

Revision ID: bd4f91633b10
Revises: f5a48fdef295
Create Date: 2020-04-20 15:09:48.202613

"""

# revision identifiers, used by Alembic.
revision = 'bd4f91633b10'
down_revision = 'f5a48fdef295'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
